id: I98818B85
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-9023
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 09:47:32.508481+00:00
last_modified: 2023-09-26 09:47:32.508489+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W7500
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW7500
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་འགྲེལ་པ།
  languages:
  - bo
  author: དཔའ་བོ ༠༢་གཙུག་ལག་འཕྲེང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9654980349582348
  ocr_word_median_confidence_index: 0.999168665
bases:
  I3560:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3560
      total_pages: 980
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3560.txt
    statistics:
      ocr_word_median_confidence_index: 0.999168665
      ocr_word_mean_confidence_index: 0.9654980349582348
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
